### ISSUE TITLE
会封号吗？？

### ISSUE THREAD

**Issue by Jackjun724** [kekeimiku/kbz#1]

**Comment by kekeimiku** [comment]
我暂时没有封过，，，可能是因为我段位低只有铂金。。

Jun Jack ***@***.***> 于2021年7月20日周二 上午1:24写道：

**Comment by Jackjun724** [comment]
> 我暂时没有封过，，可能是因为我段位低只有铂金。。另外这个项目只做研究使用，并没有对封号之类的问题进行测试，总之不推荐实际使用。。

可以分享一下逆向过程吗

**Comment by kekeimiku** [comment]
没什么好分享的，就是找到对应地址然后读取了一下而已，，
Jun Jack ***@***.***> 于2021年7月26日周一 下午5:07写道：
