### ISSUE TITLE
坐标问题

### ISSUE THREAD

**Issue by qyjava** [kekeimiku/kbz#2]
二进制获取到的是游戏矩阵坐标，但这部坐标我们该怎么转换成我们手机需要的坐标呢
希望下次更新能加入矩阵坐标转换的函数

**Comment by qyjava** [comment]
抱歉，没注意全文，里面又矩阵坐标转换

**Comment by kekeimiku** [comment]
。。。最近没太留意这个项目，回复晚了，不好意思。

**Comment by qyjava** [comment]
> 。。。最近没太我这个项目，回复晚了，不好意思。已经解决了，那个问题我先关了。

没事，您这个项目没有问题，只是我没留意到有相应的函数
